apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/about.k8s.io_clusterproperties.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# The following patch adds an annotation to pass protected groups approval required to use domain "k8s.io"
- path: patches/annotation_for_clusterproperties.yaml
